using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VOCALOIDPatcher.Formats.LibreSvip.Core;
using VOCALOIDPatcher.Formats.LibreSvip.Framework;
using VOCALOIDPatcher.Formats.LibreSvip.Model;
using VOCALOIDPatcher.Formats.LibreSvip.Serialization;

namespace VOCALOIDPatcher.Formats.LibreSvip.Plugins.Subtitle;

public sealed class AssConverter : FormatConverter
{
    public LyricSplitMode SplitBy { get; set; } = LyricSplitMode.Both;
    public bool IgnoreSlurNotes { get; set; } = true;
    public int Offset { get; set; }
    public int TrackIndex { get; set; } = -1;
    public string Encoding { get; set; } = "utf-8";

    private const string Header =
        "[Script Info]\n" +
        "; Script generated by LibreSVIP\n" +
        "ScriptType: v4.00+\n" +
        "WrapStyle: 0\n" +
        "ScaledBorderAndShadow: yes\n" +
        "PlayResX: 1920\n" +
        "PlayResY: 1080\n" +
        "\n" +
        "[V4+ Styles]\n" +
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n" +
        "Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n" +
        "\n" +
        "[Events]\n" +
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";

    public override bool CanDump => true;

    public override byte[] Dump(Project project)
    {
        var tempoList = project.SongTempoList.Count > 0
            ? project.SongTempoList
            : new List<SongTempo> { new(0, Constants.DefaultBpm) };
        var synchronizer = new TimeSynchronizer(tempoList);
        var singingTrack = TrackIndex >= 0 && TrackIndex < project.TrackList.Count
            ? project.TrackList[TrackIndex] as SingingTrack
            : project.TrackList.OfType<SingingTrack>().FirstOrDefault(t => t.NoteList.Count > 0);
        if (singingTrack == null)
            throw new InvalidOperationException("No singing track found");

        var builder = new StringBuilder(Header);
        foreach (var buffer in SubtitleSupport.SplitLines(singingTrack.NoteList, SplitBy))
        {
            int startMs = (int)(synchronizer.GetActualSecsFromTicks(buffer[0].StartPos) * 1000) - Offset;
            int endMs = (int)(synchronizer.GetActualSecsFromTicks(buffer[^1].EndPos) * 1000) - Offset;
            string text = SubtitleSupport.BuildText(buffer, IgnoreSlurNotes).Trim();
            builder.Append("Dialogue: 0,").Append(FormatTime(startMs)).Append(',').Append(FormatTime(endMs))
                .Append(",Default,,0,0,0,,").Append(text).Append('\n');
        }
        return TextHelper.GetEncoding(Encoding).GetBytes(builder.ToString());
    }

    private static string FormatTime(int totalMs)
    {
        if (totalMs < 0)
            totalMs = 0;
        int centi = totalMs % 1000 / 10;
        int totalSeconds = totalMs / 1000;
        int second = totalSeconds % 60;
        int minute = totalSeconds / 60 % 60;
        int hour = totalSeconds / 3600;
        return $"{hour}:{minute:00}:{second:00}.{centi:00}";
    }
}
